version: '3.8'
services:
  angular-client:
    build:
      context: ./angular.client
    ports:
      - "4200:4200"
    volumes:
      - ./angular.client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

  asp-server:
    build:
      context: ./asp.server
    ports:
      - "5000:5000"
    volumes:
      - ./asp.server:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    command: ["dotnet", "watch", "run"]

networks:
  default:
    driver: bridge
